docker: add clang to dep installing
libclang is used to build KBS (CoCo-AS-gRPC) version, or the error

```
 > [builder 6/7] RUN cd kbs && make AS_FEATURE=coco-as-grpc ALIYUN=false ARCH=s390x NEBULA_CA_PLUGIN=false &&     make ARCH=s390x install-kbs:
126.0   cargo:warning=See: https://github.com/rust-lang/rust-bindgen?tab=readme-ov-file#environment-variables
126.0   cargo:warning=######
126.0
126.0   --- stderr
126.0
126.0   thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-7f555b6b8ccf4919/bindgen-0.72.1/lib.rs:616:27:
126.0   Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
126.0   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
126.0 warning: build failed, waiting for other jobs to finish...
147.8 make: *** [Makefile:79: background-check-kbs] Error 101

Signed-off-by: Xynnn007 <xynnn@linux.alibaba.com>