kbs: fix config item in unit test
To fix the error

error[E0063]: missing field `extractors` in initializer of `reference_value_provider_service::Config`
Error:    --> kbs/src/config.rs:313:58
    |
313 |                         rvps_config: RvpsConfig::BuiltIn(RvpsCrateConfig{
    |                                                          ^^^^^^^^^^^^^^^ missing `extractors`

Signed-off-by: Xynnn007 <xynnn@linux.alibaba.com>