kbs/test: use sudo to call kbs-client
We get an error on CI that
```
Failed to read: /tmp/tmp.YexSnCPfrU/kbs/config/docker-compose/admin-token
Error: Permission denied (os error 13)
```

The token file is generated by docker-compose's concrete container, and
the current user does not have permission to read. Thus we need sudo
permission to read the token to call client functions.

Signed-off-by: Xynnn007 <xynnn@linux.alibaba.com>