AS: fix unit test with extra field for rvps
To fix error

error[E0063]: missing field `extractors` in initializer of `reference_value_provider_service::Config`
Error:   --> attestation-service/src/config.rs:94:42
   |
94 |         rvps_config: RvpsConfig::BuiltIn(RvpsCrateConfig {
   |                                          ^^^^^^^^^^^^^^^ missing `extractors`

Signed-off-by: Xynnn007 <xynnn@linux.alibaba.com>