Work-In-Progress: kbs-client: Extend get-resource to support other plugins
This is just a hack to be able to test the nebula_ca plugin.

$ cd kbs && make cli ATTESTER=snp-attester && make install-cli
$ docker compose up

$ kbs-client config --auth-private-key kbs/config/private.key set-resource-policy --policy-file  kbs/sample_policies/allow_all.rego
$ kbs-client get-resource --plugin-name "nebula_ca" --resource-path "credential?ip[ip]=10.9.8.2&ip[netbits]=21&name=podA"

Currently, the last command is failing reporting
Error: request unauthorized

and in the trustee log:
ERROR kbs::error] TokenVerifierError(TokenVerificationFailed { source: Cannot verify token since trusted JWK Set is empty })

I did not get to the bottom of the problem yet, but I think I may need
the PR #524 as well